### PR TITLE
Add a new title screen background

### PR DESCRIPTION
**Pull request by EthanRDoesMC**
hey you awesome people. I realize i'm not a part of the resource pack team but I took these screenshots for the menu background and thought I'd share anyway. Nice to have something new, y'know? anyway, you wouldn't hurt my feelings if you rejected this PR, but I thought i'd go ahead and make it anyway.

### CODE REVIEW

**Comment by EthanRDoesMC** [comment]
I’ve got more changes if y’all are interested

**Review by Hazard-The-AD — COMMENTED** [review]
This is pretty good, I feel the old panorama view is slightly outdated.

**Comment by EthanRDoesMC** [comment]
Should I close this PR?

**Comment by EthanRDoesMC** [comment]
closing for now as the screenshots that were supposed to fix the out of date screenshots are now out of date

**Pull request closed without merging**
